### ISSUE TITLE
help

### ISSUE THREAD

**Issue by scarabhub** [homeboyinlove/scbot#1]
есть гайд на эту тему? я всё установил, но у меня бесконечно мышка уходит вправо и ничего не скупает. также не происходит обновление

**Comment by homeboyinlove** [comment]
ахах, я хз как ты нашел это если честно, я это заливал для портфолио на
работу, гайда по запуску очевидно не будет ))

**Comment by homeboyinlove** [comment]
дай мне свой дс, тот что на гитхабе у тебя не робит
